#########################Automated tests trace#########################

self = <MEGS.Tests.CRUD.test_entity_crud_action.TestEntityBase object at 0x04260BD0>
generic_entity_test_criteria = <PyTest.InputTestCriteria.InputTestCriteria.GenericEntityTestCriteria object at 0x042DE730>
search_api = <Search.Implementation.Contract.search.SearchAPI object at 0x04260130>

    @pytest.mark.crud
    def test_create_entity(self, generic_entity_test_criteria, search_api):
        if isinstance(generic_entity_test_criteria, GenericEntityTestCriteria):
            entity = generic_entity_test_criteria.api_object
            entity.es_client = self.es_client
            _primary_key = self.es_client.edge_metadata[entity.entity_name].get_entity_primary_key_field()
    
            #Create entity
            http_response = list(entity.create_entity(params={}))
    
            #Check whether request has been performed successfully
>           self.assertHttpResponseCode(http_response)

C:\EdgeDeployment\FunctionalTests\src\MEGS\Tests\CRUD\test_entity_crud_action.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MEGS.Tests.CRUD.test_entity_crud_action.TestEntityBase object at 0x04260BD0>
http_response = [400, "Bad input data: A validation error occurred.  The value of 'currencyprecision' on record of type 'transactioncurrency' is outside the valid range."]
expected_resp_code = [200, 201, 202, 203, 204, 205, ...]

    def assertHttpResponseCode(self, http_response, expected_resp_code=range(200, 299)):
        """
            Method raise assertion exception if http response code not in expected response range
            Http response should be injection as tuple - (resp_code,resp_text)
            @param http_response:
            @param expected_resp_code: could be tuple|list|int
            @return: True or assertion exception
            """
        error_msg = "HTTP response code is outside of expected response codes - {0}".format(expected_resp_code)
        if type(expected_resp_code) == range or type(expected_resp_code) == list:
>           assert http_response[0] in expected_resp_code, error_msg
E           AssertionError: HTTP response code is outside of expected response codes - [200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298]

C:\EdgeDeployment\FunctionalTests\src\MEGS\Implementation\Assertions\GenericEntityAssertMixin.py:22: AssertionError
-------------------------------- Captured log ---------------------------------
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: GET
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/authentication
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'73bce4f4c9164851985add8927914419', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "GET /xre2113qa.nightly/api/authentication HTTP/1.1" 200 2097
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 200
requests_api.py            142 INFO     Response reason: OK
requests_api.py            143 INFO     Response time: 0:00:00.426000
EntityBase.py               96 INFO     Sending POST request..
EntityBase.py              272 DEBUG    Creating request body...
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/organization HTTP/1.1" 404 104
elasticsearch_client.py     60 WARNING  ValueWithVersion`1 entity has not been found in index xre2113qa.nightly.settings
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/activitypointer HTTP/1.1" 200 9299
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly.settings/ValueWithVersion%601/organization HTTP/1.1" 404 104
elasticsearch_client.py     60 WARNING  ValueWithVersion`1 entity has not been found in index xre2113qa.nightly.settings
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/organization/_count HTTP/1.1" 200 59
connectionpool.py          296 DEBUG    "GET /xre2113qa.nightly/_search HTTP/1.1" 200 124
EntityBase.py              383 DEBUG    Request body created:
EntityBase.py              384 DEBUG    {"exchangerate": 8927.86, "currencysymbol": "TEST French /", "currencyprecision": 126, "isocurrencycode": "TEST ", "type": "transactioncurrency", "currencyname": "TEST gljta"}
requests_api.py             76 INFO     Sending HTTP request...
requests_api.py             83 DEBUG    Method type: POST
requests_api.py             94 DEBUG    Url: http://localhost/xre2113qa.nightly/api/transactioncurrency//
requests_api.py             95 DEBUG    Headers: {'Authorization-Token': u'73bce4f4c9164851985add8927914419', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/json', 'Accept-Encoding': 'deflate, gzip'}
requests_api.py            104 DEBUG    Request body: {"exchangerate": 8927.86, "currencysymbol": "TEST French /", "currencyprecision": 126, "isocurrencycode": "TEST ", "type": "transactioncurrency", "currencyname": "TEST gljta"}
connectionpool.py          176 INFO     Starting new HTTP connection (1): localhost
connectionpool.py          344 DEBUG    "POST /xre2113qa.nightly/api/transactioncurrency// HTTP/1.1" 400 146
requests_api.py            140 INFO     Response recieved...
requests_api.py            141 INFO     Response status: 400
requests_api.py            142 INFO     Response reason: Bad Request
requests_api.py            143 INFO     Response time: 0:00:00.464000
#########################Server error trace#########################
{"index":[],"megs":[{"TimeStamp":"2014-02-18T08:30:57.134119Z","Message":"FaultException: ","ErrorLevel":"ERROR","Longdate":"2014-02-18 02:30:54.7104","ThreadId":"6  ","Logger":"AscendixRE.MEGS.ApiControllers.BaseControllers.Dynamic.DynamicEntityController`1[[DetailSchema_1.transactioncurrency, a6c3f7df403142b8b87f32c28345d74f, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]","Exception":"System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: A validation error occurred.  The value of 'currencyprecision' on record of type 'transactioncurrency' is outside the valid range. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault)."},{"TimeStamp":"2014-02-18T08:30:57.341137Z","Message":"Inner Fault Message: A validation error occurred.  The value of 'currencyprecision' on record of type 'transactioncurrency' is outside the valid range.","ErrorLevel":"ERROR","Longdate":"2014-02-18 02:30:54.7104","ThreadId":"6  ","Logger":"AscendixRE.MEGS.ApiControllers.BaseControllers.Dynamic.DynamicEntityController`1[[DetailSchema_1.transactioncurrency, a6c3f7df403142b8b87f32c28345d74f, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]","Exception":""},{"TimeStamp":"2014-02-18T08:30:57.4964005Z","Message":"Inner Fault Trace Text: \r\n[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.TargetAttributeValidationPlugin]\r\n[c754fdb4-ef2f-4f2c-b49f-186214ab4dcd: TargetAttributeValidationPlugin]\r\n\r\n","ErrorLevel":"ERROR","Longdate":"2014-02-18 02:30:54.7104","ThreadId":"6  ","Logger":"AscendixRE.MEGS.ApiControllers.BaseControllers.Dynamic.DynamicEntityController`1[[DetailSchema_1.transactioncurrency, a6c3f7df403142b8b87f32c28345d74f, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]","Exception":""},{"TimeStamp":"2014-02-18T08:30:57.5960035Z","Message":"Exception: ","ErrorLevel":"ERROR","Longdate":"2014-02-18 02:30:54.7104","ThreadId":"6  ","Logger":"AscendixRE.MEGS.ApiControllers.BaseControllers.Dynamic.DynamicEntityController`1[[DetailSchema_1.transactioncurrency, a6c3f7df403142b8b87f32c28345d74f, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]","Exception":"System.ArgumentException: Bad input data: A validation error occurred.  The value of 'currencyprecision' on record of type 'transactioncurrency' is outside the valid range.\r\n   at AscendixRE.MEGS.ApiControllers.BaseControllers.EntityControllerBase.CheckSenderFault(FaultException ex)\r\n   at AscendixRE.MEGS.ApiControllers.BaseControllers.EntityControllerBase.CreateEntity(Entity sdkEntity)\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)\r\n   at CallSite.Target(Closure , CallSite , EntityControllerBase , ICRMEntity , Object )\r\n   at AscendixRE.MEGS.ApiControllers.BaseControllers.EntityControllerBase.Post(Object entity)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)"}]}
